export const theme = ["Island Tour", "Land Tour", "Safari"];
export const activity = [
  "Swimming",
  "Running",
  "Elephant Care",
  "Snorkelling",
];
export const vehicle = [
  "Yacht",
  "Speedboat",
  "Safari",
  "Catamaran",
  "Speedcatamaran",
];
export const features = [
  "Transfer",
  "Halai Food",
  "Vegatarian Food",
];

export const sales = [
  {
    type: "TOURS",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "TOURS",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "TOURS",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "TOURS",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "TOURS",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
  },
  {
    type: "TICKETS",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "TICKETS",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "TICKETS",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "TICKETS",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "TICKETS",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
  },
  {
    type: "TRANSFER",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "TRANSFER",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "TRANSFER",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "TRANSFER",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "TRANSFER",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
    
  },
  {
    type: "RENT",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "RENT",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "RENT",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "RENT",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "RENT",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
  },
];
export const TICKETS = [
  {
    type: "TICKETS",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "TICKETS",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "TICKETS",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "TICKETS",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "TICKETS",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
  },
  {
    type: "RENT",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "RENT",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "RENT",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "RENT",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "RENT",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
  },
];

export const rent = [
  {
    type: "RENT",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "RENT",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "RENT",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "RENT",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "RENT",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
  },
];

export const transfer = [
  {
    type: "TRANSFER",
    location: "Asia",
    theme: "Island Tour",
    activity: "Swimming",
    price: "10000",
    time: "600",
    size: "10",
    vehicle: "Yacht",
    features: "Transfer",
  },
  {
    type: "TRANSFER",
    location: "Africa",
    theme: "Land Tour",
    activity: "Running",
    price: "8000",
    time: "500",
    size: "8",
    vehicle: "Speedboat",
    features: "Halai Food",
  },
  {
    type: "TRANSFER",
    location: "Europe",
    theme: "Safari",
    activity: "Elephant Care",
    price: "12000",
    time: "700",
    size: "12",
    vehicle: "Safari",
    features: "Vegatarian Food",
  },
  {
    type: "TRANSFER",
    location: "Australia",
    theme: "Island Tour",
    activity: "Snorkelling",
    price: "9500",
    time: "550",
    size: "6",
    vehicle: "Catamaran",
    features: "Transfer",
  },
  {
    type: "TRANSFER",
    location: "South America",
    theme: "Land Tour",
    activity: "Running",
    price: "11000",
    time: "650",
    size: "15",
    vehicle: "Speedcatamaran",
    features: "Halai Food",
  },
];
